server:
  port: 8087
  servlet:
    context-path: /cosmetics

spring:
  application:
    name: cosmetics
  datasource:
    url: "jdbc:mysql://localhost:3306/omamori_cosmetics"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: cosmetic-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.spa.cosmeticservice.dto.event"
        spring.json.value.default.type: com.spa.cosmeticservice.dto.event.InvoicePaidEvent
        spring.json.use.type.headers: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

cosmetic:
  kafka:
    invoice-paid-topic: invoice-paid

jwt:
  signerKey: "${JWT_SIGNER_KEY:1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij}"
