server:
  port: 8082
  servlet:
    context-path: /appointments

treatment-service:
  url: http://localhost:8083

room-service:
  url: http://localhost:8084

spring:
  application:
    name: appointment-service
  datasource:
    url: "jdbc:mysql://localhost:3306/omamori_appointment"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
